name: Update Chromium Versions

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：拉取代码（包含完整历史）
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 步骤2：清理残留文件（避免冲突）
      - name: Clean workspace
        run: |
          git reset --hard HEAD
          git clean -fd

      # 步骤3：同步远程最新代码
      - name: Pull latest code
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase

      # 步骤4：生成版本文件到 public/ 目录
      - name: Fetch LAST_CHANGE files
        run: |
          mkdir -p public  # 确保 public 目录存在
          platforms=(
            "Android" "Android_Arm64" "AndroidDesktop_arm64" "AndroidDesktop_x64"
            "Linux" "Linux_x64" "Mac" "Mac_Arm" "Win" "Win_Arm64" "Win_x64"
          )
          for platform in "${platforms[@]}"; do
            sanitized_name=$(echo "$platform" | tr '/' '_')
            curl -s "https://storage.googleapis.com/chromium-browser-snapshots/${platform}/LAST_CHANGE" -o "./public/${sanitized_name}-last-change.txt"
          done

      # 步骤5：提交变更（仅 public/ 目录）
      - name: Commit and Deploy
        run: |
          git add public/  # 仅添加 public/ 目录内的文件
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update Chromium versions"
            git push "https://${{ github.actor}}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          fi

      # 步骤6：部署到 Pages（仅发布 public/ 目录）
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # 关键：仅部署 public 目录
          publish_branch: main
          keep_files: true  # 保留目标分支现有文件
