name: Update Chromium Versions

on:
  schedule:
    - cron: "0 */2 * * *"  # 每2小时执行一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Clean workspace
        run: |
          git reset --hard HEAD
          git clean -fd
      - name: Pull latest code
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase
      - name: Fetch LAST_CHANGE files
        run: |
          mkdir -p public
          platforms=(
            "Android" "Android_Arm64" "AndroidDesktop_arm64" "AndroidDesktop_x64"
            "Linux" "Linux_x64" "Mac" "Mac_Arm" "Win" "Win_Arm64" "Win_x64"
          )
          for platform in "${platforms[@]}"; do
            sanitized_name=$(echo "$platform" | tr '/' '_')
            curl -s "https://storage.googleapis.com/chromium-browser-snapshots/${platform}/LAST_CHANGE" -o "./public/${sanitized_name}-last-change.txt"
          done
      - name: Commit changes
        run: |
          git add public/
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update Chromium versions"
            git push "https://${{ github.actor}}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          fi
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: main
          # keep_files: true
